### DAILY BOMZ ARTICLE — WRITE ONLY (NO SHELL COMMANDS)

## INPUT DATA
Read context from /home/ubuntu/bomz-articles/data/cron_context.txt.
This file was pre-generated by a shell script that already handled: git operations, date checks, RSS fetch.

Content format:
- SOURCE: rss or fallback
- HEADLINES (if rss): raw news titles
- TOPICS list (if fallback): suggested topics

## CHOOSE YOUR TOPIC
Based on the source above, select ONE topic and write an analytical essay in Indonesian about it.
Requirements:
- 700-1000 words STRICTLY. Do not exceed 1000 words.
- Natural Indonesian language. TO THE POINT. No flowery language. No clichés ("Di era digital", "Pada akhirnya").
- NO emdash (—). Use commas, periods, colons instead.
- Every claim must be backed by data/facts/statistics from verifiable sources (BPS, World Bank, OECD, IPCC, UN, Kementrian, etc.).
- Analytical depth: connect observation → data → pattern → implication → conclusion. Not listicles.
- Paragraph-based prose only. No bullet points. No numbered lists.
- No generic closing. End on a resonant analytical note.
- Content must be original analysis, not just summarizing news. Provide opinion, critique, or suggestion based on learned patterns.

## OUTPUT FORMAT

Write file to: /home/ubuntu/bomz-articles/src/content/articles/<UUID>.md

Generate UUID using any method available.

Frontmatter (first line of file):
---
id: <uuid>
slug: <url-safe-title-lowercase-hyphenated>
title: "<exact-title>"
excerpt: "<one-sentence core argument based on real data>"
author: BOMZ
date: "TODAY_DATE_FROM_CONTEXT"
category: <ONE of: Politik|Ekonomi|Teknologi|Lingkungan|Sosial|Kesehatan|Pendidikan>
---

Then immediately after frontmatter starts the essay body with heading # same as title.

## AFTER WRITING

Run these commands:
cd /home/ubuntu/bomz-articles && git add . && git commit -m "chore: publish article <id> — <title>" && git push origin main

## FINAL OUTPUT

Return JSON like this (no code fences):
{
  "id": "<uuid>",
  "slug": "<slug>",
  "title": "<title>",
  "excerpt": "<excerpt>",
  "author": "BOMZ",
  "date": "<date>",
  "category": "<category>",
  "content_path": "/home/ubuntu/bomz-articles/src/content/articles/<uuid>.md",
  "topic_source": "<rss or fallback>"
}
